<?php

return [
    'role_structure' => [
        'superadmin' => [
            'kategori' => 'c,r,u,d',
            'barang' => 'c,r,u,d',
            'pembelian' => 'c,r,u,d',
            'penjualan' => 'c,r,u,d',
            'kasir' => 'c,r,u,d',
            'PO' => 'c,r,u,d',
            'PO_detail' => 'c,r,u,d',
            'satuan' => 'c,r,u,d',
            'supplier' => 'c,r,u,d',
            'mengatur_permisi' => 'c,r,u,d',
            'karyawan' => 'c,r,u,d',
            'laporan' => 'c,r,u,d',
            'pengeluaran' => 'c,r,u,d',
            'pendapatan' => 'c,r,u,d',
            'master' => 'c,r,u,d',
            'pengguna' => 'c,r,u,d',
            'dashboard' => 'c,r,u,d',
        ],
        'owner' => [
            'kategori' => 'c,r,u,d',
            'barang' => 'c,r,u,d',
            'pembelian' => 'c,r,u,d',
            'penjualan' => 'c,r,u,d',
            'kasir' => 'c,r,u,d',
            'PO' => 'c,r,u,d',
            'PO_detail' => 'c,r,u,d',
            'satuan' => 'c,r,u,d',
            'supplier' => 'c,r,u,d',
            'mengatur_permisi' => 'c,r,u,d',
            'karyawan' => 'c,r,u,d',
            'laporan' => 'c,r,u,d',
            'pengeluaran' => 'c,r,u,d',
            'pendapatan' => 'c,r,u,d',
            'master' => 'c,r,u,d',
            'pengguna' => 'c,r,u,d',
            'dashboard' => 'c,r,u,d',
        ],
        'employee' => [
            'kategori' => 'c,r,u,d',
            'barang' => 'c,r,u,d',
            'pembelian' => 'c,r,u,d',
            'penjualan' => 'c,r,u,d',
            'kasir' => 'c,r,u,d',
            'PO' => 'c,r,u,d',
            'PO_detail' => 'c,r,u,d',
            'satuan' => 'c,r,u,d',
            'supplier' => 'c,r,u,d',
            'mengatur_permisi' => 'c,r,u,d',
            'karyawan' => 'c,r,u,d',
            'laporan' => 'c,r,u,d',
            'pengeluaran' => 'c,r,u,d',
            'pendapatan' => 'c,r,u,d',
            'master' => 'c,r,u,d',
            'pengguna' => 'c,r,u,d',
            'dashboard' => 'c,r,u,d',
        ],
    ],
    'permissions_map' => [
        'c' => 'buat',
        'r' => 'baca',
        'u' => 'rubah',
        'd' => 'hapus'
    ]
];
